package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AccuteProgramVariableAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccuteProgramVariableAllPropertiesEquals(AccuteProgramVariable expected, AccuteProgramVariable actual) {
        assertAccuteProgramVariableAutoGeneratedPropertiesEquals(expected, actual);
        assertAccuteProgramVariableAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccuteProgramVariableAllUpdatablePropertiesEquals(
        AccuteProgramVariable expected,
        AccuteProgramVariable actual
    ) {
        assertAccuteProgramVariableUpdatableFieldsEquals(expected, actual);
        assertAccuteProgramVariableUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccuteProgramVariableAutoGeneratedPropertiesEquals(
        AccuteProgramVariable expected,
        AccuteProgramVariable actual
    ) {
        assertThat(expected)
            .as("Verify AccuteProgramVariable auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccuteProgramVariableUpdatableFieldsEquals(AccuteProgramVariable expected, AccuteProgramVariable actual) {
        assertThat(expected)
            .as("Verify AccuteProgramVariable relevant properties")
            .satisfies(e -> assertThat(e.getSectionId()).as("check sectionId").isEqualTo(actual.getSectionId()))
            .satisfies(e -> assertThat(e.getSectionName()).as("check sectionName").isEqualTo(actual.getSectionName()))
            .satisfies(e -> assertThat(e.getOrderIndex()).as("check orderIndex").isEqualTo(actual.getOrderIndex()))
            .satisfies(e -> assertThat(e.getJsonSchema()).as("check jsonSchema").isEqualTo(actual.getJsonSchema()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccuteProgramVariableUpdatableRelationshipsEquals(
        AccuteProgramVariable expected,
        AccuteProgramVariable actual
    ) {
        assertThat(expected)
            .as("Verify AccuteProgramVariable relationships")
            .satisfies(e -> assertThat(e.getVersion()).as("check version").isEqualTo(actual.getVersion()));
    }
}
