package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SiteOrgTempAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteOrgTempAllPropertiesEquals(SiteOrgTemp expected, SiteOrgTemp actual) {
        assertSiteOrgTempAutoGeneratedPropertiesEquals(expected, actual);
        assertSiteOrgTempAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteOrgTempAllUpdatablePropertiesEquals(SiteOrgTemp expected, SiteOrgTemp actual) {
        assertSiteOrgTempUpdatableFieldsEquals(expected, actual);
        assertSiteOrgTempUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteOrgTempAutoGeneratedPropertiesEquals(SiteOrgTemp expected, SiteOrgTemp actual) {
        assertThat(expected)
            .as("Verify SiteOrgTemp auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteOrgTempUpdatableFieldsEquals(SiteOrgTemp expected, SiteOrgTemp actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteOrgTempUpdatableRelationshipsEquals(SiteOrgTemp expected, SiteOrgTemp actual) {
        // empty method
    }
}
