package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SiteOrganisationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteOrganisationAllPropertiesEquals(SiteOrganisation expected, SiteOrganisation actual) {
        assertSiteOrganisationAutoGeneratedPropertiesEquals(expected, actual);
        assertSiteOrganisationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteOrganisationAllUpdatablePropertiesEquals(SiteOrganisation expected, SiteOrganisation actual) {
        assertSiteOrganisationUpdatableFieldsEquals(expected, actual);
        assertSiteOrganisationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteOrganisationAutoGeneratedPropertiesEquals(SiteOrganisation expected, SiteOrganisation actual) {
        assertThat(expected)
            .as("Verify SiteOrganisation auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteOrganisationUpdatableFieldsEquals(SiteOrganisation expected, SiteOrganisation actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteOrganisationUpdatableRelationshipsEquals(SiteOrganisation expected, SiteOrganisation actual) {
        // empty method
    }
}
