package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserSiteOrganisationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSiteOrganisationAllPropertiesEquals(UserSiteOrganisation expected, UserSiteOrganisation actual) {
        assertUserSiteOrganisationAutoGeneratedPropertiesEquals(expected, actual);
        assertUserSiteOrganisationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSiteOrganisationAllUpdatablePropertiesEquals(UserSiteOrganisation expected, UserSiteOrganisation actual) {
        assertUserSiteOrganisationUpdatableFieldsEquals(expected, actual);
        assertUserSiteOrganisationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSiteOrganisationAutoGeneratedPropertiesEquals(UserSiteOrganisation expected, UserSiteOrganisation actual) {
        assertThat(expected)
            .as("Verify UserSiteOrganisation auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSiteOrganisationUpdatableFieldsEquals(UserSiteOrganisation expected, UserSiteOrganisation actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSiteOrganisationUpdatableRelationshipsEquals(UserSiteOrganisation expected, UserSiteOrganisation actual) {
        assertThat(expected)
            .as("Verify UserSiteOrganisation relationships")
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()))
            .satisfies(e -> assertThat(e.getSiteOrganisation()).as("check siteOrganisation").isEqualTo(actual.getSiteOrganisation()))
            .satisfies(e -> assertThat(e.getRole()).as("check role").isEqualTo(actual.getRole()));
    }
}
